name: structureflutter
description: A new Flutter project For Training.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1

  equatable: ^2.0.5
  connectivity: ^3.0.6

  # Resource localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  shared_preferences: ^2.0.7
  json_annotation: ^4.7.0
  http: ^0.13.3

  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  carousel_slider: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.1
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Generation resource
  generate: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Thin.ttf
          weight: 100
        - asset: assets/fonts/HelveticaNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeue-Medium.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue-Black.ttf
          weight: 900
